name: Tests

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Python 3
        uses: actions/setup-python@v4
        with: 
          python-version: 3.12

      - name: Run tests
        run: python -m unittest tests/*.py
        